---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-server-installer
  namespace: metrics-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-server-cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: metrics-server-installer
    namespace: metrics-server
---
apiVersion: olm.operatorframework.io/v1alpha1
kind: ClusterExtension
metadata:
  name: metrics-server
spec:
  source:
    sourceType: Catalog
    catalog:
      packageName: metrics-server
      version: 3.12.0
  install:
    namespace: metrics-server
    serviceAccount:
      name: metrics-server-installer